feat: update neo4j api
Bombaharris/nggql pull request #17
Opened 2024-02-06 13:29 UTC by McStOnwelo

Update API and its packages to the most recent version

2024-02-12 10:58 UTC, Bombaharris requested changes

2024-02-12 10:58 UTC, Bombaharris commented on api/src/schema.graphql
> -type PersonsToProject {
Check how this recipes works now.

2025-02-03 12:17 UTC, moose96 approved these changes
Seems it's working but do we consider updating packages once more?

 |Package|                Current|   Wanted|   Latest|
| -- | -- | -- | -- |
|@graphql-tools/schema|   10.0.2|  10.0.16|  10.0.16|
|@graphql-tools/utils|   10.0.13|   10.7.2|   10.7.2|
|@neo4j/graphql|           4.4.5|    4.4.8|    6.3.0 |
|dotenv|                  16.4.1|   16.4.7|   16.4.7|
|graphql|                 16.8.1|  16.10.0|  16.10.0|
|neo4j-driver|            5.16.0|   5.27.0|   5.27.0|

2025-02-07 10:28 UTC, moose96 commented
I've also bumped almost all other dependencies in `api` directory. `@neo4j/graphql` has been bumped to 5.x because there is many breaking changes between 5 and 6 and we'll probably face them: [https://neo4j.com/docs/graphql/6/migration/](https://neo4j.com/docs/graphql/6/migration/)

|Package|                Current|   Wanted|   Latest|
| -- | -- | -- | -- |
|@neo4j/graphql|           5.11.4|    5.11.4|    6.3.0 |

2025-02-10 11:50 UTC, merged